version: '2'
services:
  db:
    image: "mysql:8.0.15"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: local_root
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'local_app'
    volumes_from:
      - data
    ports:
      - "3306:3306"
    networks:
      - lambda-local
  data:
    image: "busybox"
    volumes:
      - "db:/var/lib/mysql"

volumes:
  db:
    driver: local

networks:
  lambda-local:
    external: true