# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  healthya_line_campaign

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  notifyEstimation:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./built/notifyEstimation
      MemorySize: 128
      Timeout: 100
      Description: HTTP post method for BodyBank Web-hook.
      Environment:
        Variables:
          DB_HOST: !Ref DB_HOST
          DB_PORT: 3306
          DB_USER: !Ref DB_USER
          DB_PASSWORD: !Ref DB_PASSWORD
          DB_NAME: !Ref DB_NAME
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v1/notify_estimation
            Method: POST
  getBodyGramToken:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./built/getBodyGramToken
      MemorySize: 128
      Timeout: 100
      Description: Get token of BodyBank API.
      Environment:
        Variables:
          DB_HOST: !Ref DB_HOST
          DB_PORT: 3306
          DB_USER: !Ref DB_USER
          DB_PASSWORD: !Ref DB_PASSWORD
          DB_NAME: !Ref DB_NAME
          hostUrl: "https://api.kao-dev.enterprise.bodybank.com"
          token: "vvgSvuKwwV3N4EQ9AX0Is8KMFwKBoV6t57YdaUmb"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v1/bodygram/token
            Method: GET
  getBodyGramEstimation:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./built/getBodyGramEstimation
      MemorySize: 128
      Timeout: 100
      Description: Get estimation result of BodyBank API.
      Environment:
        Variables:
          DB_HOST: !Ref DB_HOST
          DB_PORT: 3306
          DB_USER: !Ref DB_USER
          DB_PASSWORD: !Ref DB_PASSWORD
          DB_NAME: !Ref DB_NAME
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v1/bodygram/estimation
            Method: GET
  getEstimationLogs:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./built/getEstimationLogs
      MemorySize: 128
      Timeout: 100
      Description: Retrieve own estimation logs.
      Environment:
        Variables:
          DB_HOST: !Ref DB_HOST
          DB_PORT: 3306
          DB_USER: !Ref DB_USER
          DB_PASSWORD: !Ref DB_PASSWORD
          DB_NAME: !Ref DB_NAME
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v1/estimaton_logs
            Method: GET
  getLinePoints:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./built/getLinePoints
      MemorySize: 128
      Timeout: 100
      Description: Retrieve own line points.
      Environment:
        Variables:
          DB_HOST: !Ref DB_HOST
          DB_PORT: 3306
          DB_USER: !Ref DB_USER
          DB_PASSWORD: !Ref DB_PASSWORD
          DB_NAME: !Ref DB_NAME
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v1/line_points
            Method: GET

  usersCreate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./built/usersCreate
      MemorySize: 128
      Timeout: 100
      Description: Register own user data.
      Environment:
        Variables:
          DB_HOST: !Ref DB_HOST
          DB_PORT: 3306
          DB_USER: !Ref DB_USER
          DB_PASSWORD: !Ref DB_PASSWORD
          DB_NAME: !Ref DB_NAME
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v1/users
            Method: POST
  userMe:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./built/userMe
      MemorySize: 128
      Timeout: 100
      Description: Retrieve own user data.
      Environment:
        Variables:
          DB_HOST: !Ref DB_HOST
          DB_PORT: 3306
          DB_USER: !Ref DB_USER
          DB_PASSWORD: !Ref DB_PASSWORD
          DB_NAME: !Ref DB_NAME
      Events:
        userMeShow:
          Type: Api
          Properties:
            Path: /api/v1/users/me
            Method: GET
        userMeUpdate:
          Type: Api
          Properties:
            Path: /api/v1/users/me
            Method: PUT
Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.ap-northeast-1.amazonaws.com/prod/"
