# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  healthya_line_campaign

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # source code: notify_estimation.js
  notifyEstimationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/notify_estimation.notifyEstimationHandler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 100
      Description: HTTP post method for BodyBank Web-hook.
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/notify_estimation
            Method: POST
  # source code: token.js
  getBodyGramTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get_bodygram_token.getBodyGramTokenHandler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 100
      Description: Get token of BodyBank API.
      Environment:
        Variables:
          hostUrl: "https://api.kao-dev.enterprise.bodybank.com"
          token: "vvgSvuKwwV3N4EQ9AX0Is8KMFwKBoV6t57YdaUmb"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/get_bodygram_token
            Method: GET

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.ap-northeast-1.amazonaws.com/prod/"
